#!/bin/python
import sys
import os

BASIC_INPUT = sys.argv
FILE_PATH = "/usr/local/bin/.cnt"

if len(BASIC_INPUT) > 1:

	if BASIC_INPUT[1] == "-c":

		f = open(FILE_PATH,"r")
		s = f.read().split('__')
		for item in s:
			if item != '':
				_TEMP = item.split('#')
				if len(BASIC_INPUT) > 2:
					if BASIC_INPUT[2] == _TEMP[0]:
						_TEMP_STR = 'sftp %s@%s' % (_TEMP[1],_TEMP[2])
						os.system(_TEMP_STR)
						break;
				else:
					print("Select connection (use -l[ist])")
					break;
	elif BASIC_INPUT[1] == "add":

		f = open(FILE_PATH,"a")
		f.write("__" + BASIC_INPUT[2] + "#" + BASIC_INPUT[3] + "#" + BASIC_INPUT[4])
		print("> " + BASIC_INPUT[2] + " -> added")
		f.close()

	elif BASIC_INPUT[1] == "-l":

		f = open(FILE_PATH,"r")
		s = f.read().split('__')
		for item in s:
			if item != '':
				STR = item.split('#');
				print("> " + STR[0] + " | " + STR[1] + " | " + STR[2])

	elif BASIC_INPUT[1] == "-e":

		f = open(FILE_PATH,"r")
		s = f.read().split('__')
		for item in s:
			if item != '':
				_TEMP = item.split('#')
				if len(BASIC_INPUT) > 3:
					if BASIC_INPUT[2] == _TEMP[0]:
						_f = open(FILE_PATH,"rt")
						_data = _f.read()
						_data = _data.replace(_TEMP[1],BASIC_INPUT[3])
						_data = _data.replace(_TEMP[2],BASIC_INPUT[4])
						_s = open(FILE_PATH,'w')
						_s.write(_data)
						print("> " + _TEMP[0] + " -> replaced.")
				else:
					print("> Select connection title -l[list]")
					break;

	elif BASIC_INPUT[1] == "-d":

		f = open(FILE_PATH,"r")
		s = f.read().split('__')
		for item in s:
			if item != '':
				_TEMP = item.split('#')
				if len(BASIC_INPUT) > 1:
					if BASIC_INPUT[2] == _TEMP[0]:
						_f = open(FILE_PATH,"rt")
						_data = _f.read()
						_data = _data.replace("__" + _TEMP[0] + "#" + _TEMP[1] + "#" + _TEMP[2],'')
						_s = open(FILE_PATH,'w')
						print("> Want to delete " + _TEMP[0] + "? (y/n)")
						realy = input()
						if realy == "y":
							_s.write(_data)
							print("> " + _TEMP[0] + " -> deleted")
							_s.close()
						else:
							_s.close()
else:

	print('Connecto v 1.0 \n')
	print('> -c[onnect] + connection name \n')
	print('> -l[ist] to show connection \n')
	print('> add [connection title] [user] [host] to add connection\n')
	print('> -e[dit] [connection title] [user] [host] edit connection\n')
	print('> -d[elete] [connection title] delete connection')
	print('\n')
